// Data migrated from the existing static HTML (index.html + Faheem-uddin.html)
// so the database starts populated with exactly what's already live.
// Edit any of this any time from the admin dashboard after seeding —
// this file is only ever used once, to bootstrap the database.

const advocates = [
  {
    slug: 'faheem-uddin',
    name: 'Adv. Faheem Uddin',
    designation: 'Senior MACT Lawyer & Motor Accident Claims Specialist',
    court: 'Kanpur Court',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    experience_years: 15,
    cases_won: 500,
    rating: 4.9,
    review_count: 347,
    success_rate: 96,
    languages: ['Hindi', 'English', 'Urdu', 'Arabic'],
    practice_tags: ['MACT Expert', 'Road Accident Compensation', 'Insurance Claim Disputes'],
    consultation_fee: 2500,
    fee_unit: 'session',
    is_available: true,
    is_featured: true,
    bar_council_text: 'Bar Council of U.P. Registered',
    photo_url: 'Faheem .jpg',
    short_bio:
      "Advocate Faheem Uddin is Kanpur's most trusted Motor Accident Claims Tribunal (MACT) lawyer, renowned for securing maximum compensation for accident victims and their families. With over 15 years of dedicated practice in motor accident law, insurance disputes, and personal injury claims across Uttar Pradesh, he has earned a reputation for relentless advocacy, transparent counsel, and exceptional client results.",
    long_bio: [
      'Advocate Faheem Uddin has built a distinguished legal career spanning over 15 years, specializing exclusively in Motor Accident Claims Tribunal (MACT) cases, road accident compensation, and insurance dispute resolution across Uttar Pradesh. Based in Kanpur, he practices regularly before the Kanpur District Court, Kanpur Court, and various UP Motor Accident Tribunals.',
      'His deep expertise in the Motor Vehicles Act, insurance law, and personal injury jurisprudence allows him to construct powerful legal arguments that consistently deliver maximum compensation for his clients. Whether it is a fatal accident case, permanent disability claim, or a complex multi-party insurance dispute — Adv. Faheem approaches every matter with the same rigor and dedication.',
      'What sets him apart is his client-first philosophy: transparent fee structures, regular case updates, Hindi-medium communication for local clients, and a genuine commitment to securing justice rather than simply settling cases. He has personally secured compensation ranging from Rs. 5 lakh to Rs. 1.2 crore for individual clients.',
    ],
    quote:
      'Every accident victim deserves justice. My job is to ensure the law works for them — not against them. I will not rest until my client receives every rupee they are entitled to.',
    quote_attribution: 'Adv. Faheem Uddin, Senior MACT Lawyer, Kanpur',
    why_choose: [
      { title: '15+ Years of MACT Expertise', desc: 'Dedicated exclusively to motor accident and compensation law — no generalist shortcuts.' },
      { title: '96% Compensation Success Rate', desc: 'Clients receive full, fair, and timely compensation — verified by tribunal records.' },
      { title: 'Fast Legal Action — 24hr Response', desc: 'Time-sensitive accident cases are handled with urgency. Available on WhatsApp and phone daily.' },
      { title: 'Client-Friendly Hindi Consultation', desc: 'Explains complex legal rights in simple Hindi — no legal jargon, no confusion.' },
      { title: 'No Hidden Charges — Zero Surprise Fees', desc: 'Complete fee transparency from day one. You know exactly what you pay and why.' },
      { title: 'Kanpur Court & Kanpur Tribunal Expert', desc: 'Practises daily before Kanpur courts, MACT tribunals, and the Kanpur Court.' },
    ],
    practice_areas: [
      { title: 'Motor Accident Claims (MACT)', desc: 'Complete representation before Motor Accident Claims Tribunals across Kanpur and surrounding divisions.' },
      { title: 'Road Accident Compensation', desc: 'Securing maximum compensation for car, bike, truck, and pedestrian accident victims under the Motor Vehicles Act.' },
      { title: 'Insurance Claim Disputes', desc: 'Fighting insurance companies that wrongfully deny, delay, or underpay accident compensation claims.' },
      { title: 'Injury & Disability Compensation', desc: 'Claiming full compensation for temporary and permanent disabilities and loss of income.' },
      { title: 'Fatal Accident Compensation', desc: 'Representing bereaved families in accidental death claims — dependant compensation and future income losses.' },
      { title: 'Hit & Run Cases', desc: 'Claiming compensation under the Solatium Fund where the offending vehicle is unidentified.' },
      { title: 'Legal Notice & Claim Filing', desc: 'Drafting legal notices, filing MACT petitions, and handling paperwork from FIR to final award.' },
      { title: 'Motor Vehicle Act Cases', desc: 'Handling offences and disputes under the Motor Vehicles Act 1988, including licence and permit disputes.' },
    ],
    fee_structure: [
      {
        name: 'Initial Consultation', type: '30-Minute Legal Assessment',
        original_price: '₹1,000', price: '₹599', save_text: '40% OFF — Today Only',
        inclusions: ['Full case evaluation by Adv. Faheem', 'Claim strength assessment', 'Compensation estimate', 'Action plan for your case', 'Hindi or English — your choice'],
        featured: false, button_text: 'Book Now',
      },
      {
        name: 'MACT Full Case Handling', type: 'From FIR to Final Award',
        original_price: '₹25,000', price: '₹14,999', save_text: 'Save ₹10,001 — Limited Time',
        inclusions: ['Complete MACT petition filing', 'All tribunal hearings', 'Insurance company negotiation', 'Medical evidence documentation', 'Case updates via WhatsApp'],
        featured: true, button_text: 'Get This Package',
      },
      {
        name: 'Insurance Dispute Package', type: 'Claim Denial / Underpayment',
        original_price: '₹15,000', price: '₹9,499', save_text: 'Save ₹5,501 — 37% OFF',
        inclusions: ['Insurance policy analysis', 'Dispute notice drafting', 'Consumer forum representation', 'High Court appeal if needed'],
        featured: false, button_text: 'Book Now',
      },
    ],
    achievements: [
      { title: 'Rs. 12 Crore+ Total Compensation Secured', desc: 'Across 500+ MACT cases, Adv. Faheem has secured over Rs. 12 crore in combined compensation for accident victims and bereaved families.' },
      { title: '96% Success Rate in MACT Tribunals', desc: 'An industry-leading success rate across 500+ cases in Kanpur and surrounding districts.' },
      { title: 'Kanpur Court Appearance — Record Award', desc: 'Successfully appealed a tribunal award in 2021, securing enhanced compensation of Rs. 1.2 crore for a permanently disabled victim.' },
      { title: 'Recognised by Kanpur Bar Association', desc: 'Commended for outstanding contribution to motor accident victim advocacy and pro-bono legal assistance (2019 & 2022).' },
    ],
    reviews: [
      { name: 'Ramesh Kumar Verma', case: 'Fatal Accident Claim — Kanpur · Rs. 18 Lakh Awarded', text: 'Insurance company rejected the claim after my brother\u2019s accidental death. Adv. Faheem secured Rs. 18 lakh compensation in 8 months. A dedicated and honest lawyer.' },
      { name: 'Sanjay Mishra', case: 'Permanent Disability Claim — Unnao · Rs. 24 Lakh', text: 'After a truck accident left me with 60% permanent disability, Adv. Faheem built a strong MACT case and secured Rs. 24 lakh. Always available on WhatsApp.' },
      { name: 'Naseema Begum', case: 'Hit & Run Case — Kanpur · Solatium Fund', text: 'It was a hit-and-run case with no driver traced. Adv. Faheem secured compensation through the Solatium Fund and explained the entire process patiently.' },
    ],
    phone: '+918948143948',
    whatsapp: '+918948143948',
    email: 'fhmlegalsolution@gmail.com',
    address: 'Kanpur, UP',
    sort_order: 1,
  },
  {
    slug: 'priya-sharma',
    name: 'Adv. Priya Sharma',
    designation: 'Senior Advocate · Delhi High Court',
    court: 'Delhi High Court',
    city: 'Delhi, NCR',
    state: 'Delhi',
    experience_years: 18,
    rating: 4.9,
    review_count: 218,
    success_rate: 92,
    languages: ['Hindi', 'English'],
    practice_tags: ['Family Law', 'Divorce', 'Child Custody'],
    consultation_fee: 1500,
    fee_unit: 'session',
    is_available: true,
    photo_url: 'lawyer_cabin.jpg',  // replace via admin panel
    short_bio: 'Senior advocate practising family and matrimonial law before the Delhi High Court, with 18 years of experience in divorce, custody, and maintenance matters.',
    phone: '+918948143948',
    whatsapp: '+918948143948',
    sort_order: 2,
  },
  {
    slug: 'shahnawaz-muzaffar-barkati',
    name: 'Adv. Shahnawaz Muzaffar Barkati',
    designation: 'Advocate · High Court & District Courts',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    experience_years: 6,
    rating: 4.8,
    review_count: 305,
    success_rate: 89,
    languages: ['Hindi', 'English', 'Urdu'],
    practice_tags: ['Criminal & Civil', 'Matrimonial & RTI', 'Labour & Drafting'],
    consultation_fee: 2500,
    fee_unit: '15 mins',
    is_available: true,
    photo_url: 'shahnawaz.png',
    short_bio: 'Advocate practising criminal, civil, matrimonial, and RTI matters before the High Court and District Courts.',
    phone: '+918948143948',
    whatsapp: '+918948143948',
    sort_order: 3,
  },
  {
    slug: 'ananya-krishnan',
    name: 'Adv. Ananya Krishnan',
    designation: 'Corporate & Startup Counsel · Bangalore',
    city: 'Bangalore',
    state: 'Karnataka',
    experience_years: 12,
    rating: 4.7,
    review_count: 186,
    success_rate: 95,
    languages: ['English', 'Kannada'],
    practice_tags: ['Corporate Law', 'Startups', 'Contracts'],
    consultation_fee: 2200,
    fee_unit: 'session',
    is_available: false,
    photo_url: 'lawyer_cabin.jpg',
    short_bio: 'Corporate counsel advising startups and businesses on incorporation, contracts, and compliance.',
    phone: '+918948143948',
    whatsapp: '+918948143948',
    sort_order: 4,
  },
  {
    slug: 'mohd-salman-khan',
    name: 'Adv. Mohd Salman Khan',
    designation: 'MACT & Tax Advocate · Kanpur Nagar',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    experience_years: 6,
    rating: 4.9,
    review_count: 274,
    success_rate: 91,
    languages: ['Hindi', 'Urdu', 'English'],
    practice_tags: ['MACT Claims', 'GST', 'Income Tax'],
    consultation_fee: 2000,
    fee_unit: '15 mins',
    is_available: true,
    photo_url: 'Mohd Salman Khan.jpg',
    short_bio: 'Advocate handling motor accident claims alongside GST and income tax matters in Kanpur Nagar.',
    phone: '+918948143948',
    whatsapp: '+918948143948',
    sort_order: 5,
  },
  {
    slug: 'sunitha-reddy',
    name: 'Adv. Sunitha Reddy',
    designation: 'Cyber Crime & IT Law Expert · Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    experience_years: 9,
    rating: 4.8,
    review_count: 142,
    success_rate: 88,
    languages: ['Telugu', 'English', 'Hindi'],
    practice_tags: ['Cyber Crime', 'Data Privacy', 'IT Act'],
    consultation_fee: 1800,
    fee_unit: 'session',
    is_available: false,
    photo_url: 'lawyer_cabin.jpg',
    short_bio: 'Specialist in cyber crime, data privacy, and IT Act litigation based in Hyderabad.',
    phone: '+918948143948',
    whatsapp: '+918948143948',
    sort_order: 6,
  },
  {
    slug: 'arjun-datta',
    name: 'Adv. Arjun Datta',
    designation: 'Labour & Employment Specialist · Kolkata',
    city: 'Kolkata',
    state: 'West Bengal',
    experience_years: 15,
    rating: 4.6,
    review_count: 198,
    success_rate: 87,
    languages: ['Bengali', 'Hindi', 'English'],
    practice_tags: ['Labour Law', 'Employment', 'HR Disputes'],
    consultation_fee: 900,
    fee_unit: 'session',
    is_available: true,
    photo_url: 'lawyer_dealing.webp',
    short_bio: 'Labour and employment law specialist representing both employees and employers in Kolkata.',
    phone: '+918948143948',
    whatsapp: '+918948143948',
    sort_order: 7,
  },
  {
    slug: 'saira-khan',
    name: 'Adv. Saira Khan',
    designation: 'Criminal Defence Specialist · New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    experience_years: 18,
    rating: 4.7,
    review_count: 212,
    success_rate: 92,
    languages: ['Hindi', 'English'],
    practice_tags: ['Criminal Law', 'Anticipatory Bail', 'FIR'],
    consultation_fee: 1200,
    fee_unit: 'session',
    is_available: true,
    photo_url: 'lawyer_saira.jpg',
    short_bio: 'Criminal defence advocate handling bail applications, FIR quashing, and trial representation in New Delhi.',
    phone: '+918948143948',
    whatsapp: '+918948143948',
    sort_order: 8,
  },
];

const practiceAreas = [
  { title: 'Family & Divorce', description: '620+ Lawyers' },
  { title: 'Property & Real Estate', description: '485+ Lawyers' },
  { title: 'Criminal Defence', description: '530+ Lawyers' },
  { title: 'Corporate & Business', description: '410+ Lawyers' },
  { title: 'Banking & Finance', description: '290+ Lawyers' },
  { title: 'Labour & Employment', description: '340+ Lawyers' },
  { title: 'Medical Negligence', description: '180+ Lawyers' },
  { title: 'Consumer Rights', description: '270+ Lawyers' },
  { title: 'Cyber Crime & IT', description: '195+ Lawyers' },
  { title: 'GST & Taxation', description: '320+ Lawyers' },
  { title: 'Visa & Immigration', description: '150+ Lawyers' },
  { title: 'Startup & Contracts', description: '230+ Lawyers' },
  { title: 'Cheque Bounce', description: '380+ Lawyers' },
  { title: 'Land & Agriculture', description: '220+ Lawyers' },
  { title: 'Intellectual Property', description: '165+ Lawyers' },
  { title: 'Constitutional Law', description: '120+ Lawyers' },
].map((row, i) => ({ ...row, sort_order: i + 1, is_active: true }));

const homepageContent = {
  hero: {
    heading: "India's Most Trusted Legal Platform",
    subheading: 'Connect with verified, bar-council-registered advocates across India for transparent, expert legal help.',
  },
  stats: {
    items: [
      { number: 5000, suffix: '+', label: 'Verified Lawyers' },
      { number: 50000, suffix: '+', label: 'Cases Resolved' },
      { number: 200, suffix: '+', label: 'Cities Covered' },
      { number: 96, suffix: '%', label: 'Client Satisfaction' },
    ],
  },
  footer: {
    tagline: "India's Legal Bridge",
    phone: '+91 89481 43948',
    email: 'fhmlegalsolution@gmail.com',
    whatsapp: '+918948143948',
  },
  site_settings: {
    site_name: 'FHM-Legal-Solution',
    logo_url: 'fhm_logo.png',
    social_links: { facebook: '', instagram: '', twitter: '', linkedin: '' },
  },
};

const testimonials = [];

module.exports = { advocates, practiceAreas, homepageContent, testimonials };
